name: Rebuild With New SDK

on:
  push:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
  pull_request:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.event_name  }}
  cancel-in-progress: true

jobs:
  payload-build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Checkout pacbrew-repo
      uses: actions/checkout@v4
      with:
        repository: EchoStretch/pacbrew-repo
        path: pacbrew-repo

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          autoconf \
          automake \
          build-essential \
          clang-18 \
          curl \
          git \
          libarchive-tools \
          libtool \
          lld-18 \
          makepkg \
          meson \
          nasm \
          pacman-package-manager \
          pkg-config \
          xxd \
          yasm

    - name: Build PS5 payload SDK
      working-directory: pacbrew-repo/sdk
      run: |
        makepkg -c -f
        sudo pacman --noconfirm -U ./ps5-payload-*.pkg.tar.gz

    - name: Build PS5 sqlite package
      working-directory: pacbrew-repo/sqlite
      run: |
        makepkg -c -f
        sudo pacman --noconfirm -U ./ps5-payload-*.pkg.tar.gz

    - name: Build Payload
      run: |
        export PS5_PAYLOAD_SDK=/opt/ps5-payload-sdk
        bash ci-ps5-kstuff-ldr.sh

    - name: Upload Payload
      uses: actions/upload-artifact@v4
      with:
        name: Payload
        path: ./ps5-kstuff-ldr/kstuff.elf
        if-no-files-found: error
